name: Create Release on Tag

on:
    push:
        tags:
            - '*'

jobs:
    release:
        name: Create GitHub Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Validate Gradle wrapper
              uses: gradle/actions/wrapper-validation@v4

            - name: Setup JDK
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'microsoft'
            
            - name: Make Gradle executable
              run: chmod +x ./gradlew

            - name: Build
              run: ./gradlew build
            
            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                tag_name: ${{ github.ref_name }}
                files: build/libs/discordwebhook-[0-9]*.jar
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}